apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-app-ingress
  annotations:
    # Prod용 그룹 이름
    alb.ingress.kubernetes.io/group.name: backend-prod
spec:
  rules:
  - host: api.fall-in-jeju.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-app-service
            port:
              number: 80

